'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './pages/navbar';
import Footer from './pages/footer';
import { useEffect, useState } from 'react';
import NavbarMobile from './pages/navbarMobile';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const [width, setWidth] = useState(0);

  useEffect(() => {
    setWidth(window.innerWidth);
  });
  return (
    <html className='flex flex-col' lang='en'>
      <body>
        {width >= 1280 ? (
        <Navbar className='h-auto'>{children}</Navbar>
        ) : (
          <NavbarMobile className='h-auto'>{children}</NavbarMobile>
        )}
      </body>
    </html>
  );
}
